ConnectGlobe1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('MyApp.urls', namespace='MyApp')),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),

    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
         name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

MyApp/urls.py
from django.urls import path
from MyApp import views
from django.contrib.auth import views as auth_views

app_name = 'MyApp'

urlpatterns = [
    path('postComment/', views.postComment, name='postComment'),
    path('contact/', views.contact1, name='contact'),
    path('posts/', views.view_posts, name='view_posts'),
    path('area/', views.your_area, name='your_area'),
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('reg/', views.reg, name='reg'),
    path('logout/', views.logout, name='logout'),
    path('post_report/', views.post_report, name='post_report'),
    path('about/',views.about1, name='about'),
    path('showp/',views.seeprofile,name='showp'),
    path('job/', views.job1, name='jobs'),
    path('dev_info/',views.dev_info,name='dev_info'),
    path('<pk>/', views.detail_view, name='detail'),





    # path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
    # name='password_reset'), path('password-reset/done', auth_views.PasswordResetDoneView.as_view(
    # template_name='password_reset_done.html'),name='password_reset_done'),

]

MyApp/models.py
# Create your models here.
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now




class Post(models.Model):
    title = models.CharField(max_length=200, blank=False, null=False)
    body = models.TextField(max_length=10000, blank=False, null=False)
    date_posted = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey(User, default=None, blank=True, null=True, on_delete=models.CASCADE)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title


class Contact(models.Model):
    contact_first = models.CharField(max_length=225)
    contact_last = models.CharField(max_length=225)
    contact_email = models.CharField(max_length=225)
    contact_subject = models.CharField(max_length=225)
    contact_feedback = models.CharField(max_length=225)



class Job(models.Model):
    job_name = models.CharField(max_length=225)
    job_email = models.CharField(max_length=225)
    job_country = models.CharField(max_length=225)
    job_contact = models.BigIntegerField(default=0)
    job_tech = models.CharField(max_length=225)
    job_exp = models.IntegerField(default=0)
    job_company = models.CharField(max_length=225)
    job_qual = models.CharField(max_length=225)
    job_resume = models.FileField(upload_to='resume',null=True)

    def __str__(self):
        return self.job_name

class UProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    email = models.CharField(max_length=100)
    image = models.ImageField(upload_to='pics',null=True, default='default.jpg')
    dob = models.DateTimeField(null=True)
    desc = models.CharField(max_length=225)
    city = models.CharField(max_length=225)



class PostComment(models.Model):
    objects = models.Manager()
    sno = models.AutoField(primary_key=True)
    comment = models.TextField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='replies')
    timestamp = models.DateTimeField(default=now)

templates/about.html
{% extends 'index.html'%}
{% load static %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body background="{% static 'images/p6.jpeg'%}">
<h1>About Us</h1>
<p>
    Connect Globe provides a common people can share their experiences,Information and hurdles all over the globe and people can consult and discuss on any topic that is created by only the registered user.
    Moreover the user can give their precious advice on any topic or report.
    The admin after being logged in can created and also post any topic or report that is to be discussed.
    Admin also can view old comments history and post his own comment on topics.
    common people can view reports after being logged in and can share the report and also post and view comments.
</p>

</body>
</html>

{% endblock content %}

templates/contact.html
{% extends 'index.html'%}
{% load static %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact Us</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body background="{% static 'images/p6.jpeg'%}">
<div class="container" style="text-align:center;margin-top:5%;margin-left:100px;margin-bottom: 20px;">
     <h1 style="text-align:center;border-bottom:2px;margin-left:50px;">Contact Form</h1><br> <br>
    <form method="post">
        {% csrf_token %}
        {% if messages %}
        {% for message in messages%}
        <p style="color:green; text-align: center;">{{message}}</p>
        {% endfor %}
        {% endif %}



          <br><input type="text" name="firstname" placeholder="First Name" required style="height:50px;width:450px;border-radius:2px;margin-top:-20px;"><br><br>
            <input type="text" name="lastname" placeholder="Last Name" required style="height:50px;width:450px;border-radius:2px;margin-top:-20px;"><br><br>
            <input type="text" name="email" placeholder="Email" pattern="[^@\s]+@[^@\s]+\.[^@\s]+" title="Please fill out this field" required style="height:50px;width:450px;border-radius:2px;margin-top:-20px;"><br><br>
            <input type="text" name="subject" placeholder="Subject" required style="height:50px;width:450px;border-radius:2px;margin-top:-20px;"><br><br>
            <input type="text" name="feedback" placeholder="Feedback" required style="height:100px;width:450px;border-radius:2px;margin-top:-20px;"><br><br>

        <input type="Submit" value="&nbsp;&nbsp;Submit&nbsp;" id="sub2" style="margin-left:3px;border-radius:10px;width:100px;background-color:white;">
    </form>
</div>
</body>
</html>
{% endblock content %}

templates/detail.html
{% load static %}
{% load humanize %}
{% load extras %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail Posts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<div class="container">
    <body background="{% static 'images/p6.jpeg' %}">
    <h1 style="text-align:center">Detail Posts</h1>
    <h2>{{ post.title }}</h2>
    <p>{{ post.body }}</p>
    <small><b>{{ post.author }}</b></small>
    <small>{{ post.date_posted }}</small>

    <form class="form-wrapper" action="{% url 'MyApp:postComment' %}" method="post">
        {% csrf_token %}
        <br><textarea class="form-control" name="comment"
                      placeholder="Write Your comment"></textarea><br>
        <input type="hidden" name="postpk" value="{{ post.pk }}">
        <input type="hidden" name="parentpk" value="">
        <button type="submit" class="btn btn-primary">Submit Comment</button>
        <br><br>
    </form>
    {% for comment in comments %}
        <div class="media">
            <a class="media-left" href="#">
            </a>
            <div class="media-body">
                <h4 class="media-heading user_name">{{ comment.user.username }}
                    <small>{{ comment.timestamp | naturaltime }}</small>
                </h4>
                <p>{{ comment.comment }}</p>
                <div class="reply mx-0">
                    <button class="btn btn-primary btn-sm" type="button"
                            data-toggle="collapse"
                            data-target="#replyBox{{ comment.pk }}"
                            aria-expanded="False"
                            aria-controls="replyBox{{ comment.pk }}">Reply
                    </button>
                    <button class="btn btn-primary btn-sm" type="button"
                            data-toggle="collapse"
                            data-target="#replyView{{ comment.pk }}"
                            aria-expanded="False"
                            aria-controls="replyView{{ comment.pk }}">View/Hide
                        Replies
                    </button>
                    <div class="collapse" id="replyBox{{ comment.pk }}">
                        <div class="card card-body my-2">
                            <form class="form-wrapper"
                                  action="{% url 'MyApp:postComment' %}"
                                  method="post">
                                {% csrf_token %}
                                <label for="comment">Post a Reply</label>
                                <textarea class="form-control" name="comment"
                                          placeholder="Write Your comment..."></textarea>
                                <input type="hidden" name="parentpk"
                                       value="{{ comment.pk }}">
                                <input type="hidden" name="postpk"
                                       value="{{ post.pk }}"><br>
                                <button type="submit" class="btn btn-primary">
                                    Submit Reply
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="media-body my-2 mx-3"
                         id="replyView{{ comment.pk }}">
                        {% for reply in replydict|get_val:comment.pk %}
                            <div style="margin-bottom: 0.005%">
                                {{ reply.comment }}
                                by<span><b> {{ reply.user.username }}</b></span>
                            </div>
                            <br>


                        {% endfor %}
                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
</div>
</div>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

templates/dev_info.html
{% extends 'index.html' %}
{% block content %}


  {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body background="{% static 'images/p5.jpeg'%}">
<div class="header">
    <section class="container-fluid">

        <form method="post" enctype="multipart/form-data" class="form-container">
            {% csrf_token %}
            <div class="form-group">
                <h1 style="text-align:center">Developer Info.</h1>
                <label><h1>Heena Chhabra</h1></label>
                <h1>Patel Institute Of Management and Technology, Rajpura</h1>
                <h1>MCA</h1><br><br>



                <label><h1>Raman Dhindsa</h1></label>
                <h1>Patel Institute Of Management and Technology, Rajpura</h1>
                <h1>MCA</h1>

            </div>

        </form>
    </section>
</div>
</body>
</html>
{% endblock content %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Connect Globe</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <link rel="stylesheet" href="{% static 'fonts/icomoon/flaticon.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <script src="https://kit.fontawesome.com/9ae01dec74.js" crossorigin="anonymous"></script>


    <link rel="stylesheet" href="{% static 'css/basic.css' %}">

</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

<div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>


    <header class="site-navbar py-4 bg-white js-sticky-header site-navbar-target" role="banner">

        <div class="container">
            <div class="row align-items-center">

                <div class="col-11 col-xl-2">
                    <h1 class="mb-0 site-logo"><a href="/index" class="text-black h2 mb-0" style="text-decoration:none;">Connect
                        Globe<span class="text-primary">.</span> </a></h1>
                </div>
                <div class="col-12 col-md-10 d-none d-xl-block">
                    <nav class="site-navigation position-relative text-right" role="navigation">

                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                           <li><a href="{% url 'MyApp:index' %}" class="nav-link">Home</a></li>
                <li><a href="{% url 'MyApp:view_posts' %}" class="nav-link">View Status</a></li>
                <li>
                  {% if request.user.is_authenticated %}
                  <a href="{% url 'MyApp:post_report' %}" class="nav-link">Post Report</a>
                </li>

                <li><a href="{% url 'MyApp:your_area' %}" class="nav-link">Your Area</a></li>
                <li><a href="{% url 'MyApp:contact' %}" class="nav-link">Contact</a></li>
                <li><a href="{% url 'MyApp:jobs' %}" class="nav-link">Jobs</a></li>
                <li><a href="{%url 'MyApp:logout' %}">Logout</a></li>
      <li>Hello,{{user.first_name}}</li>
      {% else %}
                <li><a href="{% url 'MyApp:reg' %}">Register</a></li>
<li><a href="{% url 'MyApp:login' %}">Login</a></li>
      {% endif %}
                        </ul>
                    </nav>
                </div>


                <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a
                        href="#" class="site-menu-toggle js-menu-toggle text-black"><span
                        class="icon-menu h3"></span></a></div>

            </div>
        </div>

    </header>




{% block content %}
    <div class="site-blocks-cover overlay" style="background-image: url({% static 'images/hero_1.jpg' %});"
         data-aos="fade" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row align-items-center justify-content-center text-center">

                <div class="col-md-12" data-aos="fade-up" data-aos-delay="400">

                    <div class="row justify-content-center mb-4">
                    </div>

                </div>
            </div>
        </div>
    </div>
    <section class="site-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-4">
                    <div class="p-3 box-with-humber">
                        <div class="number-behind">01.</div>
                        <i class="fas fa-question fa-3x mb-3 text-primary"></i>
                        <h2 class="text-primary">Ask Questions</h2>
                        <p class="mb-4">Ask a technical questions publicly on CONNECT GLOBE to get knowledge.</p>

                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="p-3 box-with-humber">
                        <div class="number-behind">02.</div>
                        <i class="fas fa-edit fa-3x mb-3 text-primary"></i>
                        <h2 class="text-primary">Answer Questions</h2>
                        <p class="mb-4">Answer a question to share your technical knowledge with the world .</p>

                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="p-3 box-with-humber">
                        <div class="number-behind">03.</div>
                        <i class="fas fa-search fa-3x mb-3 text-primary"></i>
                        <h2 class="text-primary">Tag Your Answer</h2>
                        <p class="mb-4">Tags help make information searchable and find answers that are important to you.</p>

                    </div>
                </div>
            </div>
        </div>
    </section>

 <!--.site-wrap -->


{% endblock content %}
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-5">
                            <h2 class="footer-heading mb-4">Website Feature</h2>
                            <p>Helping write the script of the future by serving developers and all technologists to help solve coding problems, develop new skills.</p>
                        </div>
                        <div class="col-md-3 ml-auto">

                            <h2 class="footer-heading mb-4">Other Features</h2>
                              <ul class="list-unstyled">
                                    <li><a href="{% url 'MyApp:about' %}">About Us</a></li>
                                    <li><a href="{% url 'MyApp:contact' %}">Contact Us</a></li>
                                    <li><a href="{% url 'MyApp:dev_info' %}">Developer_Info</a></li>
                                    <li><a href="{% url 'MyApp:showp' %}">Profile</a></li>
                              </ul>

                        </div>
                    </div>
                </div>
            </div>
        </div>
</footer>

    </div> <!-- .site-wrap -->

<script src="{% static 'javas/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'javas/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'javas/jquery-ui.js' %}"></script>
<script src="{% static 'javas/popper.min.js' %}"></script>
<script src="{% static 'javas/bootstrap.min.js' %}"></script>
<script src="{% static 'javas/jquery.stellar.min.js' %}"></script>
<script src="{% static 'javas/jquery.countdown.min.js' %}"></script>
<script src="{% static 'javas/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'javas/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'javas/aos.js' %}"></script>
<script src="{% static 'javas/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'javas/jquery.sticky.js' %}"></script>

<script src="{% static 'javas/typed.js' %}"></script>

<script src="{% static 'javas/main.js' %}"></script>


</body>

</html>

templates/login.html
{% extends 'index.html' %}
{% block content %}


  {% load static %}
<style type="text/css">
body{
    background-image: url('/static/images/p5.jpeg');
}

.login-form{
    width: 40%;
    margin-bottom: 10%;
    box-sizing: border-box;
    padding: 40px;
    margin-left: 25%;
    margin-top: 10%;
    transition: 0.5s;
    background: rgba(0,0,0,0.8);
    border-radius: 18px;
    box-shadow: 0 15px 25px rgba(0,0,0,0.5);
}
h1 {
    margin: 0 0 20px;
    font-size: 35px;
    text-align: center;
    text-transform: uppercase;
    font-family: 'Baloo Thambi 2',cursive;
}
.login-form input {
     display:block;
     width: 100%;
     padding: 20px 20px;
     box-sizing: border-box;
     margin-bottom: 20px;
     border-radius:2px;
     outline: none;
     font-size: 18px;
     color:#fff;
     background:transparent;
}

.login-form input:hover{
     border: 1px dotted #fff;

}

.login-form input::placeholder{
      color: #E5E5E5;
      font-family: 'Lobster', cursive;

}

.login-form input[type="submit"]{
       color:#fff;
       font-family: 'Baloo Thambi 2', cursive;
       font-size:22px;
       background: #03a9f4;
       border: none;
       cursor:pointer;
       text-transform:uppercase;
       font-weight:bold;
       margin-top: 10%;
}
.login-form input[type="submit"]:hover {
       background: #2bbac4;

}

.login-form #a {
       width: 100%;
       margin-bottom: 0px;
       margin-left: 25%;
       text-decoration: none;
       color: #fff;
       font-size: 18px;
       border: none;
       cursor: pointer;
       text-transform: uppercase;
       form-family: 'Baloo Thambi 2';
       font-weight: bold;
 }

</style>
<body>

<section>
    <div class="container">
        <div class="login-form">
            <h1>LOGIN</h1>
            <form method="post">
            {% csrf_token %}
            <input type="text" name="name" placeholder="USER NAME" required/>
            <input type="password" name="pass" placeholder="PASSWORD" required/>

            <input type= "submit" value="LOGIN">
            <h2 style="color: #fff; text-align : center; ">OR</h2>
                <a  href= "{% url 'MyApp:reg' %}"><u style="color:#fff; text-align : center;">REGISTER HERE</u></a>
               <br><br>
            <b style="color:#fff; word-spacing:2px; ">Please register first</b>
            <a  href= "{% url 'MyApp:reg' %}"><u style="margin-left:10px;color:#fff;  ">REGISTER HERE</u></a>
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                        <p style="color: white; text-align: center; ">{{ message }}</p>
                    {% endif %}
                {% endfor %}
        </form>

        </div>
    </div>
</section>
</body>


{% endblock content %}

templates/password_reset.html
<!DOCTYPE html>

  {% load static %}
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body background="{% static 'images/p5.jpeg' %}">
<section>
    <div class="container">
        <div class="login-form">
            <h1>Reset Your Password</h1>
            <form method="post">{% csrf_token %}
        <input type="text" name="Email Id" placeholder="Email Id" required>

            <input type= "submit" value="Reset Password">


        </form>

        </div>
    </div>
</section>
</body>
</html>

templates/password_reset_done.html
<!DOCTYPE html>
 {% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
   {% csrf_token %}
<div class ="alert alert-info">
An email has been set with instructions to reset your password
</div>

</body>
</html>

templates/post_report.html
{% extends 'index.html'%}
{% load static %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post_Report</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body background="{% static 'images/p6.jpeg'%}">

    <h2 style="text-align:center">ADD POST</h2>
    <div class="container" style="margin-bottom: 10%; margin-top:5%;margin-left:500px;width:50px;">
        <div class="row">

            <div class="col-lg-7 offset-lg-1">
                {% if message %}
                    <p style="color:#0e5b44; margin-left:150px;width:50px;"><i>{{ message}}</i></p>
                {% endif %}
                <form class="create-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- title -->
                    <div class="form-group">
                        <label for="id_image"><h3 style="left:70%;">Title</h3></label>
                        {{ post_form.title|safe }}
                    </div>
                    <br>

                    <!-- Body -->

                    <div class="form-group">
                        <label for="id_image"><h3 style="float:center;left:50%;">Body</h3></label>
                        {{ post_form.body|safe }}
                    </div>

                    <!-- Image -->


                    <input type="Submit" value="&nbsp;&nbsp;Post&nbsp;" style="margin-left:100px;border-radius:10px;width:100px;background-color:white;">
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock content %}

templates/view_area.html
{% extends 'index.html'%}
{% load static %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Area</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body background="{% static 'images/p6.jpeg'%}">
{% if request.user %}
{% for post in posts %}
<h3>{{ post.title }}</h3>
<p>{{ post.body }}</p>
<small><b>{{ post.author }}</b></small>
<small>{{ post.date_posted }}</small>
{% endfor %}
{% endif %}

</body>
</html>
{% endblock content %}

templates/view_status.html
{% extends 'index.html'%}
{% load static %}

{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Posts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body background="{% static 'images/h2.jpg'%}">
<div class="container">
<h1 style="text-align:center">View Posts</h1>
{% for post in posts %}
<h2><a href="{% url 'MyApp:detail' post.pk %}">{{post.title}}</a></h2>
<p>{{post.body}}</p>
<small><b>{{post.author}}</b></small>
<small>{{ post.date_posted }}</small>
{% endfor %}
</div>
</body>
</html>

{% endblock content %}